### PR TITLE
QZ-766 Return email content blocks in place of html

### PR DESCRIPTION
**Pull request by itjhai-qz**

### CODE REVIEW

**Review by adamhooper — COMMENTED** [review]
@itjhai-qz That looks wonderful ... but the iOS App refers to `EmailParts` (as opposed to `EmailTeaserParts`) in `Quartz/Modules/Article/ArticleDisplayModel.swift`. What would happen if `qz-ios` were to upgrade to a version of `Quartz/content` after this change is made?

**Comment by itjhai-qz** [comment]
@adamhooper — I'd guess that the `qz-ios` build would fail with the new version, as the `qz-ios` would read several properties that are no longer part of `EmailParts`, though I'm not really sure. If this is the case, the dev updating the iOS app needs to make the necessary changes to make it work.

Do we ever update the `qz-ios` recently? Would you suggest we test building the ios app?

**Comment by adamhooper** [comment]
@itjhai-qz we never update the iOS app. Hopefully we'll delete it. However, we've kept a respectful distance so far....

Options:

1. Protect future iOS devs from hassle (probably): use `EmailParts` everywhere instead of `EmailTeaserParts`. _consequences_: some queries are slower; and we can't know for sure this actually preserves iOS compilation.
2. Declare, with fanfare, that `Quartz/content` no longer supports `qz-ios`. Major-version bump, rah rah. _consequences_: we merge this PR and get this feature out the door; but `Quartz/content` becomes 100% terrible, as it no longer even pretends to share queries between `qz-ios` and `qz-react`.
3. Move any queries we edit to `Quartz/qz-react` instead of `Quartz/content`. _consequences_: we need to figure out some qz-react tooling; development becomes faster in the future.

Personally, I always thought this repo was a mistake. We're going to do 3 eventually. But it may be the most work? Dunno. All options seem okay to me. @ramesh-kumar @itjhai-qz shall we make a final call in standup this morning?

**Comment by adamhooper** [comment]
Since TypeScript can't use graphql loaders, I think the best tooling would be a pair of rules in the `qz-react` repo:

1. Developers who edit queries must process them using `graphql-codegen`
2. We add a GitHub Action for validation: "generated queries are up-to-date." logic: 1. copy all generated code to a temp dir; 2. re-run graphql-codegen; 3. diff the directories: they must be identical.

**Comment by sezgi** [comment]
> @itjhai-qz we never update the iOS app. Hopefully we'll delete it. However, we've kept a respectful distance so far....
> 
> Options:
> 
> 1. Protect future iOS devs from hassle (probably): use `EmailParts` everywhere instead of `EmailTeaserParts`. _consequences_: some queries are slower; and we can't know for sure this actually preserves iOS compilation.
> 2. Declare, with fanfare, that `Quartz/content` no longer supports `qz-ios`. Major-version bump, rah rah. _consequences_: we merge this PR and get this feature out the door; but `Quartz/content` becomes 100% terrible, as it no longer even pretends to share queries between `qz-ios` and `qz-react`.
> 3. Move any queries we edit to `Quartz/qz-react` instead of `Quartz/content`. _consequences_: we need to figure out some qz-react tooling; development becomes faster in the future.
> 
> Personally, I always thought this repo was a mistake. We're going to do 3 eventually. But it may be the most work? Dunno. All options seem okay to me. @ramesh-kumar @itjhai-qz shall we make a final call in standup this morning?

#3 makes the most sense if we're not planning on supporting any other clients than `qz-react` in the near future; but not if we want to future-proof things

**Comment by adamhooper** [comment]
> https://github.com/Quartz/content/pull/3 makes the most sense if we're not planning on supporting any other clients than qz-react in the near future; but not if we want to future-proof things

I disagree: I don't think `Quartz/content` helps us with future-proofing.

But that's mainly because I don't understand what `Quartz/content` is for, at _all_. What's its purpose?

If `Quartz/content`'s purpose is to "standardize our data-access patterns," then it's at odds with GraphQL itself. We should standardize data-access patterns using our GraphQL schema. Our _schema_ is meant to be reusable; but each _query_ should be tied to a task in a codebase. GraphQL's number-one feature is: [Ask for what you need, get exactly that](https://graphql.org/).

In other words: if two codebases share the a query, they should use it _identically_. I'm skeptical. Do qz-ios and qz-react render _identical_ components? No: they render _similar_ components. Maybe one renders author badges and the other doesn't. Even with a tiny difference like that, editing queries for qz-react breaks qz-ios. So `Quartz/content` is a collection of accidents waiting to happen.

GraphQL is designed for [colocated fragments](https://www.apollographql.com/docs/react/data/fragments/#colocating-fragments). The idea is, a React sub-component's props can be declared as GraphQL fragments; and the parent component's GraphQL query will be auto-generated based on those fragments. So the parent's code doesn't store the full query: the query is generated at compile time based on the sub-components' props. In sum: Apollo is designed so we don't actually maintain a repo of fragments _anywhere_.

As far as I know, `Quartz/content` was created to solve a few problems:

1. De-duplicate code -- for elegance, not maintainability. This PR where we're commenting hints at how much this de-duplication costs. This repo is expensive to maintain. And this repo's creators didn't know about colocated fragments.
2. Fixing cache bugs -- Hal (the first committer) told me that a user might see one version of article metadata in qz-ios and a _different_ version in qz-react, and `Quartz/content` fixes this bug. His theory was: if qz-ios and qz-react perform the exact same query, they should get the exact same results. But that theory is false false false false false. Caching causes problems; this library neither helps nor hinders.
3. Running `graphql-codegen`. But incorporating this repo into a codebase is at _least_ as awkward as invoking graphql-codegen in the codebase itself.

**Comment by sezgi** [comment]
@adamhooper good points, queries can differ. in that case I'd vote for a cooldown task where we bring the whole thing into the `qz-react` codebase, similar to plans for `interface` and `styles` repos

**Comment by sezgi** [comment]
> @adamhooper good points, queries can differ. in that case I'd vote for a cooldown task where we bring the whole thing into the `qz-react` codebase, similar to plans for `interface` and `styles` repos

or keep separate repos, which might be cleaner, and use `git submodules` instead of npm packages

**Comment by sezgi** [comment]
that said, i don't have experience with git submodules to recommend or not. this random person (+Netflix) seem to advocate for monorepo: https://stackoverflow.com/a/62605719

**Comment by adamhooper** [comment]
Let's not use submodules. Submodules have the same purpose as npm, but with a whole different set of commands and whatnot. The single-developer experience is a little different (you can "just edit"), and the multi-developer experience is worse (parent-repo PRs contain a git hash instead of an npm version number).

**Comment by itjhai-qz** [comment]
Agree with @sezgi. We can address this during the cool-down period to bring the graphql queries into qz-react.

**Comment by itjhai-qz** [comment]
Created a follow-up ticket to tackle during the cool-down period:
- [Move graphql queries to qz-react](https://linear.app/qz/issue/QZ-879/move-graphql-queries-to-qz-react)

**Review by sezgi — APPROVED** [review]
approving commits after Adam's review, so as to unblock this PR, with superficial understanding of this repo

**Pull request merged**
